[versions]
mokoGradlePluginVersion = "0.6.0"

kotlinVersion = "2.0.20"
androidGradlePluginVerison = "8.3.2"
mobileMultiplatformVersion = "0.14.4"
detektVersion = "1.23.7"
nexusPublishVersion = "2.0.0"

[libraries]
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePluginVerison" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
mobileMultiplatformGradlePlugin = { module = "dev.icerock:mobile-multiplatform", version.ref = "mobileMultiplatformVersion" }
detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektVersion" }
nexusPublishGradlePlugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexusPublishVersion" }
